### ISSUE TITLE
Empresas en las Sucursales

### ISSUE THREAD

**Issue by Dledesma106** [Dledesma106/sistema-administrativo-random#14]
Actualmente para saber que empresas trabajan en una sucursal tenes que entrar a editarla o intentar agregar un mantenimiento preventivo o tarea
Estaría bueno agregar una columna que muestre las empresas que trabajan en cada sucursal, como se muestran los meses impuestos en un preventivo o los técnicos asignados al preventivo

**Comment by lucianinadev** [comment]
Listo
