### ISSUE TITLE
Indicacion de carga en la pagina

### ISSUE THREAD

**Issue by Dledesma106** [Dledesma106/sistema-administrativo-random#2]
La idea es que presente algún símbolo o modal de carga para indicar que la pagina esta cargando para que no parezca que se colgó

algunos ejemplos de donde implementar:
Cuando tiene que cargar el sidebar por entrar a la pagina ya logueado
Cuando cuando creamos un nuevo usuario o reseteamos la contraseña de ese usuario(esto seria en la rama email-password)

**Comment by Dledesma106** [comment]
Estilizar la pantalla de carga

**Comment by lucianinadev** [comment]
Se centro y se cambio loading por una animacion spinner
