### ISSUE TITLE
Acomodar formulario de cambio de contraseña

### ISSUE THREAD

**Issue by Dledesma106** [Dledesma106/sistema-administrativo-random#23]
![image](https://user-images.githubusercontent.com/69930982/226472235-8d1ffbd3-2afe-4b24-933b-3d9b8cfde161.png)

Queda medio raro que en ajustes lo unico que se pueda hacer es poner una contraseña y una nueva contraseña... capaz habria que denotar mejor la seccion de cambio de contraseña, o que no se llame ajustes y se llame solo cambio de contraseña

Por otro lado, habria que ajustar las letras de los labels en los inputs, con respecto al titulo de la tarjeta

**Comment by TextC0de** [comment]
Arreglado en #34
